### ISSUE TITLE
AssertionError: cxcalc bin path couldn't be detected, please specify the bin_path argument

### ISSUE THREAD

**Issue by pramodkp** [flc/cxcalc-py#1]
Hey 

**I was trying to use this tool and set default_bin_paths as my cxcalc bin folder but I am getting error as following :**
>>> from cxcalc import CollectCalculator
>>> from cxcalc.contrib.lists import get_all_plugins
>>> smiles = "N1C2C=C(C=CC=2OC(C)C1=O)NC(COC1=CC=C(C(C)=C1)C)=O"
>>> calc = CollectCalculator(plugins=get_all_plugins())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cadd/Bioinfo/cxcalc-py/cxcalc/base.py", line 254, in __init__
    super(CollectMixin, self).__init__(*args, **kwargs)
  File "/home/cadd/Bioinfo/cxcalc-py/cxcalc/base.py", line 199, in __init__
    super(Calculator, self).__init__(*args, **kwargs)
  File "/home/cadd/Bioinfo/cxcalc-py/cxcalc/base.py", line 41, in __init__
    raise AssertionError(
AssertionError: cxcalc bin path couldn't be detected, please specify the bin_path argument

**I have set default_bin_paths of base.py file as below** 
default_bin_paths = [
        '/home/pramod/opt/chemaxon/jchemsuite/bin/',
        '~/opt/chemaxon/jchemsuite/bin/',
        os.path.join(
            os.environ.get("VIRTUAL_ENV", "~"), "marvinbeans", "bin", "cxcalc"
        )
    ]
    default_options = ""

**Comment by flc** [comment]
Try to init the calculator by passing the `bin_path` argument. Like this:
```
calc = CollectCalculator(plugins=get_all_plugins(), bin_path='/home/pramod/opt/chemaxon/jchemsuite/bin/cxcalc')
```
